---
# Provider for generating traffic from linux system
#
- name: Copy packet dictionary from ansible controller to traffic source
  copy:
    src: "{{ tgn_flows_filepath }}"
    dest: "/tmp/tgn_flows.yaml"

- name: Send traffic from port
  send_traffic:
      src: "/tmp/tgn_flows.yaml"
      port: "{{ tgn_out_port }}"
      gateway: "{{ tgn_l3_gateway }}"
      wildcard_dest: "{{ tgn_wildcard_dest }}"
  become: yes
